# -*- coding: utf-8 -*-
"""10 - statsmodels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCxbnFUj_p-SIxBI-hwrrixt7WNXwLL8
"""

import pandas as pd
import requests
import numpy as np
from matplotlib import pyplot as plt
from statsmodels.regression.linear_model import OLS

beta=1
N=100
x=5+np.random.rand(N)
data=pd.DataFrame({'y':-3+beta*x+np.random.rand(N), 'x':x})
data

"""# Oppgave 1"""

beta=0.22
N=100
x=5+np.random.rand(N)
data=pd.DataFrame({'y':-3+beta*x+np.random.rand(N), 'x':x})

y=data['y']
x=pd.DataFrame(data['x'])
x['intercept']=1

res=OLS(y, x).fit()

print(res.summary())

res.params

"""Det virker å være at en beta på 0.2 og under produserer statistisk insignifikante resultater

# Oppgave 2
"""

# Siden det ikke sto i oppgaven at vi ikke kan gjøre det så velger jeg å bruke samme data fra oppgaven om scraping

# Kode kopiert fra forrige oppgave
#Laster inn pakker
import pandas as pd
import requests
from bs4 import BeautifulSoup
import csv

# Jeg blir å skrape fra http://books.toscrape.com/, som er en nettside laget for å øve seg å scrape data
# Definerer funksjoner for å få hentet data
def scrape_books(url):
    # Det er flere sider, så må hente flere URL'er for å få med alt
    all_books = []

    while True:
        # Ber om HTTP
        try:
            response = requests.get(url)
        except requests.RequestException as e:
            print(e)
            break

        # Henter html innhold
        soup = BeautifulSoup(response.content, 'html.parser')

        # Henter dette
        for listing in soup.find_all("article", class_="product_pod"):
            rating = listing.find('p', class_='star-rating')['class'][1]  # Får med "rating"
            title = listing.find('img')['alt']
            price = listing.find('p', class_="price_color").text
            inStock = "yes" if "In stock" in listing.find('p', class_="instock availability").get_text(strip=True) else "no"
            all_books.append([rating, title, price, inStock])

        # bruker html-scraping for å finne knappen til neste side
        next_button = soup.find("li", class_="next")
        if next_button:
            url = "http://books.toscrape.com/catalogue/" + next_button.find("a")["href"]
        else:
            break  # Når det ikke lengre er en neste knapp så stopper den

    return all_books


def save_books_to_csv(books):
    # Lagrer dataen per siste deloppgave
    with open('data.csv', 'w+', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["rating", "title", "price", "inStock"])
        writer.writerows(books)
    print("Data written to 'data.csv'.")

# Kjører alt
start_url = "http://books.toscrape.com/catalogue/page-1.html"
books = scrape_books(start_url)
save_books_to_csv(books)

# Lagrer data i dataframe
df = pd.DataFrame(books)
df.columns = ["rating", "title", "price", "inStock"]

# Gjør noe artig med dataen, sjekker antall bøker per rating
from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('rating').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

# Gjør noe annet artig med dataen, sjekker avg pris per rating, og
# Gjør pris om til tall/float
df['price'] = df['price'].replace('[£]', '', regex=True).astype(float)

# Finner gjennomsnittelig pris per rating
avg_price_per_rating = df.groupby('rating')['price'].mean()

# Kategoriserer etter pris
sorted_prices = df['price'].sort_values()
cheap_threshold = sorted_prices.iloc[99]  # 100 billigste
expensive_threshold = sorted_prices.iloc[-100]  # 100 dyreste

# Kategoriserer etter prisene
def categorize_price(price):
    if price <= cheap_threshold:
        return 'Cheap'
    elif price >= expensive_threshold:
        return 'Expensive'
    else:
        return 'Normal'

# Setter sammen
df['price_category'] = df['price'].apply(categorize_price)

# Finer gjennomsnittelig pris per kategori
avg_price_per_category = df.groupby('price_category')['price'].mean()

# Resultater
print("Average Price per Rating:")
print(avg_price_per_rating)
print("\nBooks in each Price Category:")
print(avg_price_per_category)

#Lagrer i df og som csv

avg_price_df = pd.DataFrame(avg_price_per_rating)
price_category_df = pd.DataFrame(avg_price_per_category)

avg_price_df.to_csv('average_prices_per_rating.csv', index=False)
price_category_df.to_csv('books_per_price_category.csv', index=False)

"""KI har blitt brukt for å optimalisere kode"""

df

import statsmodels.api as sm

# Gjør ratings om fra ord til tall
rating_to_number = {
    'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5
}
df['numeric_rating'] = df['rating'].map(rating_to_number)

# Definerer avhengig variabel (y) og uavhengig variabel (x)
y = df['price']
x = df['numeric_rating']
x = sm.add_constant(x)  # Legger til en konstant

# OLS
model = sm.OLS(y, x).fit()

print(model.summary())

"""Vi ser fra regresjonsmodellen at R-squared er veldig lav (0.001). Dette betyr at det er lite sammenheng mellom prisen på en bok og dens rating.
P-verdien er også ganske høy (0.374) som indikerer at modellen ikke er statistisk signifikant.
"""